/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Presenter.ExamPresenter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Hasancan
 */
public class ExamFrame extends javax.swing.JInternalFrame implements IExam{

    /**
     * Creates new form SinavOlustur
     */
    private static ExamFrame instance = new ExamFrame();
    
    private ExamPresenter presenter; 
    
    public ExamFrame() {
        this.setVisible(true);
        initComponents();
        presenter = new ExamPresenter(this);
    }

    public static ExamFrame getFrame(){
        return instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtExamName = new javax.swing.JTextField();
        txtExamCategory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboBoxLesson = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        comboBoxLevel = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtMultiple = new javax.swing.JTextField();
        txtClassic = new javax.swing.JTextField();
        txtTrueFalse = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtExamScore = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnPrepareExam = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listExam = new javax.swing.JList();
        btnMakeExam = new javax.swing.JButton();
        btnDeleteListViewSelectedItem = new javax.swing.JButton();
        btnAddRandomQuestion = new javax.swing.JButton();
        btnChooseFile = new javax.swing.JButton();
        lblFile = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        comboBoxExamLocation = new javax.swing.JComboBox<>();
        comboBoxSupervisor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setTitle("Exam");

        jLabel1.setText("Enter exam name :");

        jLabel2.setText("Enter exam category :");

        txtExamName.setToolTipText("Sınav adı giriniz..");

        txtExamCategory.setToolTipText("Sınav kategorisi giriniz..");

        jLabel5.setText(" Exam location :");

        jLabel6.setText("Supervisor information :");

        jLabel7.setText("Lesson :");

        comboBoxLesson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Level :");

        comboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EASY", "NORMAL", "HARD" }));

        jLabel9.setText("Kinds of questions ");

        txtMultiple.setToolTipText("Test yüzdesi");
        txtMultiple.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtClassic.setToolTipText("Klasik yüzde");

        txtTrueFalse.setToolTipText("Doğru-yanlış yüzde");

        jLabel10.setText("Exam score :");

        txtExamScore.setToolTipText("Sınav puanı giriniz..");

        jLabel11.setText("(%(test,classic,boolean)) ");

        btnPrepareExam.setText("Prepare Exam");
        btnPrepareExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepareExamActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listExam);

        btnMakeExam.setText("Make Exam");
        btnMakeExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeExamActionPerformed(evt);
            }
        });

        btnDeleteListViewSelectedItem.setText("Delete Question");
        btnDeleteListViewSelectedItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteListViewSelectedItemActionPerformed(evt);
            }
        });

        btnAddRandomQuestion.setText("Add Question");
        btnAddRandomQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRandomQuestionActionPerformed(evt);
            }
        });

        btnChooseFile.setText("Choose StudentList");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });

        lblFile.setText("Dosya Bekleniyor ...");

        jScrollPane2.setViewportView(jList1);

        comboBoxExamLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxSupervisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExamCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtExamScore, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(txtExamName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel11))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPrepareExam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtClassic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTrueFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(btnChooseFile))
                                        .addGap(21, 21, 21)
                                        .addComponent(lblFile)
                                        .addGap(0, 109, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboBoxExamLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboBoxSupervisor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton1)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteListViewSelectedItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddRandomQuestion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMakeExam, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtExamScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtExamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtExamCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboBoxLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(comboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClassic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrueFalse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrepareExam))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteListViewSelectedItem)
                    .addComponent(btnAddRandomQuestion))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChooseFile)
                    .addComponent(lblFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboBoxExamLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMakeExam)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteListViewSelectedItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteListViewSelectedItemActionPerformed
        // TODO add your handling code here:
        presenter.btnDeleteListViewSelectedItem();
    }//GEN-LAST:event_btnDeleteListViewSelectedItemActionPerformed

    private void btnPrepareExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepareExamActionPerformed
        // TODO add your handling code here:
        presenter.btnPrepareExam();
    }//GEN-LAST:event_btnPrepareExamActionPerformed

    private void btnMakeExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeExamActionPerformed
        // TODO add your handling code here:
        presenter.btnMakeExam();
    }//GEN-LAST:event_btnMakeExamActionPerformed

    private void btnAddRandomQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRandomQuestionActionPerformed
        presenter.btnAddRandomQuestion();
// TODO add your handling code here:
    }//GEN-LAST:event_btnAddRandomQuestionActionPerformed

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        // TODO add your handling code here:
        presenter.btnChooseFile();
    }//GEN-LAST:event_btnChooseFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        presenter.addExamClassInformation();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRandomQuestion;
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnDeleteListViewSelectedItem;
    private javax.swing.JButton btnMakeExam;
    private javax.swing.JButton btnPrepareExam;
    private javax.swing.JComboBox<String> comboBoxExamLocation;
    private javax.swing.JComboBox comboBoxLesson;
    private javax.swing.JComboBox comboBoxLevel;
    private javax.swing.JComboBox<String> comboBoxSupervisor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFile;
    private javax.swing.JList listExam;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField txtClassic;
    private javax.swing.JTextField txtExamCategory;
    private javax.swing.JTextField txtExamName;
    private javax.swing.JTextField txtExamScore;
    private javax.swing.JTextField txtMultiple;
    private javax.swing.JTextField txtTrueFalse;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTxtExamScore() {
        return txtExamScore.getText().toString();
    }

    @Override
    public String getTxtExamName() {
        return txtExamName.getText().toString();
    }

    @Override
    public String getTxtExamCategory() {
        return txtExamCategory.getText().toString();
    }

   

    @Override
    public String getLessonSelectedItem() {
        return comboBoxLesson.getSelectedItem().toString();
    }

    @Override
    public String getLevelSelectedItem() {
        return comboBoxLevel.getSelectedItem().toString();
    }

    @Override
    public String getTxtMultipleChoicePercent() {
        return txtMultiple.getText().toString();
    }

    @Override
    public String getTxtClassicPercent() {
        return txtClassic.getText().toString();
    }

    @Override
    public String getTxtTrueFalsePercent() {
        return txtTrueFalse.getText().toString();
    }

    @Override
    public JButton btnMakeExam() {
        return btnMakeExam;
    }

    @Override
    public JButton btnPrepareExam() {
        return  btnPrepareExam;
    }

    @Override
    public JList setListViewPreparedExamQuestions() {
        return listExam;
    }

    @Override
    public JButton btnDeleteListViewSelectedItem() {
        return btnDeleteListViewSelectedItem;
    }

    @Override
    public JButton btnAddRandomQuestion() {
        return btnAddRandomQuestion;
    }

    @Override
    public JComboBox setLessonComboBox() {
        return comboBoxLesson;
    }

    @Override
    public JOptionPane showOptionPane() {
        return new JOptionPane();
    }

    @Override
    public void setLabelFile(String text) {
        this.lblFile.setText(text);
    }

    @Override
    public String getLabelFileName() {
        return lblFile.getText();
    }

    @Override
    public JList listViewExamClasses() {
        return jList1;
    }

    @Override
    public JComboBox comboBoxSupervisor() {
        return comboBoxSupervisor;
    }

    @Override
    public JComboBox comboBoxClassRoom() {
        return comboBoxExamLocation;
    }
    
    

   

    
}
