/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Presenter.LessonOperationsPresenter;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Hasancan
 */
public class LessonOperationsFrame extends javax.swing.JInternalFrame implements ILessonOperations{

    /**
     * Creates new form LessonOperationsFrame
     */
    private static LessonOperationsFrame instance = new LessonOperationsFrame();
    private LessonOperationsPresenter presenter;
    
    
    public LessonOperationsFrame() {
        initComponents();
        this.setVisible(true);
        presenter = new LessonOperationsPresenter(this);
    }
    
    public static LessonOperationsFrame getFrame()
    {
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxLesson = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtLesson = new javax.swing.JTextField();
        btnAddLesson = new javax.swing.JButton();
        btnDeleteLesson = new javax.swing.JButton();
        btnUpdateLesson = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboBoxLecturer = new javax.swing.JComboBox<>();

        setTitle("Lesson Operations");

        comboBoxLesson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLessonActionPerformed(evt);
            }
        });

        jLabel1.setText("Lesson :");

        txtLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLessonActionPerformed(evt);
            }
        });

        btnAddLesson.setText("Add");
        btnAddLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLessonActionPerformed(evt);
            }
        });

        btnDeleteLesson.setText("Delete");
        btnDeleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLessonActionPerformed(evt);
            }
        });

        btnUpdateLesson.setText("Update");
        btnUpdateLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLessonActionPerformed(evt);
            }
        });

        jLabel2.setText("Lecturer :");

        comboBoxLecturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(comboBoxLecturer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLesson)
                    .addComponent(btnDeleteLesson)
                    .addComponent(btnUpdateLesson))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLessonActionPerformed
        // TODO add your handling code here:
        presenter.btnAddLesson();
    }//GEN-LAST:event_btnAddLessonActionPerformed

    private void btnDeleteLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLessonActionPerformed
        // TODO add your handling code here:
        presenter.btnDeleteLesson();
    }//GEN-LAST:event_btnDeleteLessonActionPerformed

    private void btnUpdateLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLessonActionPerformed
        // TODO add your handling code here:
        presenter.btnUpdateLesson();
    }//GEN-LAST:event_btnUpdateLessonActionPerformed

    private void comboBoxLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLessonActionPerformed
        // TODO add your handling code here:
        presenter.comboBoxSelectedItem();
    }//GEN-LAST:event_comboBoxLessonActionPerformed

    private void txtLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLessonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLessonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLesson;
    private javax.swing.JButton btnDeleteLesson;
    private javax.swing.JButton btnUpdateLesson;
    private javax.swing.JComboBox<String> comboBoxLecturer;
    private javax.swing.JComboBox comboBoxLesson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtLesson;
    // End of variables declaration//GEN-END:variables

   

    @Override
    public JButton btnAddLesson() {
        return btnAddLesson;
    }

    @Override
    public JButton btnDeleteLesson() {
        return btnDeleteLesson;
    }

    @Override
    public JButton btnUpdateLesson() {
        return btnUpdateLesson;
    }

    @Override
    public JComboBox fillLessons() {
        return comboBoxLesson;
    }

    @Override
    public void setTxtLesson(String lesson) {
        txtLesson.setText(lesson);
    }

    @Override
    public String getTxtLesson() {
        return txtLesson.getText();  
    }

    @Override
    public JComboBox comboBoxLecturer() {
        return comboBoxLecturer;
    }
}
