/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Hasancan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSoruEkle = new javax.swing.JMenu();
        menuTest = new javax.swing.JMenuItem();
        menuKlasik = new javax.swing.JMenuItem();
        menuBoolean = new javax.swing.JMenuItem();
        menuSinavOlustur = new javax.swing.JMenu();
        sinavOlustur = new javax.swing.JMenuItem();
        menuDersIslemleri = new javax.swing.JMenu();
        lessonOperations = new javax.swing.JMenuItem();
        questionOperations = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuizMaker");

        Desktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        menuSoruEkle.setText("Add Question");

        menuTest.setText("Multiple Choice");
        menuTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTestActionPerformed(evt);
            }
        });
        menuSoruEkle.add(menuTest);

        menuKlasik.setText("Classic");
        menuKlasik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKlasikActionPerformed(evt);
            }
        });
        menuSoruEkle.add(menuKlasik);

        menuBoolean.setText("True-False");
        menuBoolean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBooleanActionPerformed(evt);
            }
        });
        menuSoruEkle.add(menuBoolean);

        jMenuBar1.add(menuSoruEkle);

        menuSinavOlustur.setText("Exam");
        menuSinavOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSinavOlusturActionPerformed(evt);
            }
        });

        sinavOlustur.setText("Make Exam");
        sinavOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinavOlusturActionPerformed(evt);
            }
        });
        menuSinavOlustur.add(sinavOlustur);

        jMenuBar1.add(menuSinavOlustur);

        menuDersIslemleri.setText("Operations");

        lessonOperations.setText("Lesson Operations");
        lessonOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonOperationsActionPerformed(evt);
            }
        });
        menuDersIslemleri.add(lessonOperations);

        questionOperations.setText("Question Operations");
        questionOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionOperationsActionPerformed(evt);
            }
        });
        menuDersIslemleri.add(questionOperations);

        jMenuItem1.setText("Supervisor Operations");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuDersIslemleri.add(jMenuItem1);

        jMenuItem2.setText("Lecturer Operations");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuDersIslemleri.add(jMenuItem2);

        jMenuItem3.setText("ClassroomOperations");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuDersIslemleri.add(jMenuItem3);

        jMenuBar1.add(menuDersIslemleri);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void menuTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTestActionPerformed
        // TODO add your handling code here:
        Desktop.removeAll();
        Desktop.updateUI();
        Desktop.add(MultipleChoiceFrame.getFrame());
    }//GEN-LAST:event_menuTestActionPerformed

    private void menuKlasikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKlasikActionPerformed
        // TODO add your handling code here:
        Desktop.removeAll();
        Desktop.updateUI();
        Desktop.add(ClassicFrame.getFrame());
    }//GEN-LAST:event_menuKlasikActionPerformed

    private void menuBooleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBooleanActionPerformed
        // TODO add your handling code here:
        Desktop.updateUI();
        Desktop.removeAll();
        Desktop.add(TrueFalseFrame.getFrame());
    }//GEN-LAST:event_menuBooleanActionPerformed

    private void menuSinavOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSinavOlusturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSinavOlusturActionPerformed

    private void sinavOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinavOlusturActionPerformed
        // TODO add your handling code here:        
        Desktop.updateUI();
        Desktop.removeAll();
        Desktop.add(ExamFrame.getFrame());
    }//GEN-LAST:event_sinavOlusturActionPerformed

    private void questionOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionOperationsActionPerformed
        // TODO add your handling code here:
        Desktop.updateUI();
        Desktop.removeAll();;
        Desktop.add(QuestionOperationsFrame.getFrame());
    }//GEN-LAST:event_questionOperationsActionPerformed

    private void lessonOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonOperationsActionPerformed
        // TODO add your handling code here:
        Desktop.updateUI();
        Desktop.removeAll();
        Desktop.add(LessonOperationsFrame.getFrame());
    }//GEN-LAST:event_lessonOperationsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Desktop.updateUI();
        Desktop.removeAll();
        Desktop.add(SupervisorOperationsFrame.getFrame());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Desktop.updateUI();
        Desktop.removeAll();
        Desktop.add(LecturerOperationsFrame.getFrame());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Desktop.updateUI();
        Desktop.removeAll();
        Desktop.add(ClassRoomOperations.getFrame());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem lessonOperations;
    private javax.swing.JMenuItem menuBoolean;
    private javax.swing.JMenu menuDersIslemleri;
    private javax.swing.JMenuItem menuKlasik;
    private javax.swing.JMenu menuSinavOlustur;
    private javax.swing.JMenu menuSoruEkle;
    private javax.swing.JMenuItem menuTest;
    private javax.swing.JMenuItem questionOperations;
    private javax.swing.JMenuItem sinavOlustur;
    // End of variables declaration//GEN-END:variables
}
