/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Presenter.QuestionOperationsPresenter;
import java.awt.event.MouseAdapter;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JRadioButton;

/**
 *
 * @author Hasancan
 */
public class QuestionOperationsFrame extends javax.swing.JInternalFrame implements IQuestionOperations{

    /**
     * Creates new form NewJInternalFrame
     */
    private static QuestionOperationsFrame instance = new QuestionOperationsFrame();
    private QuestionOperationsPresenter presenter;
            
    public QuestionOperationsFrame() {
        initComponents();      
        presenter = new QuestionOperationsPresenter(this);
        this.setVisible(true); 
    }
    
    public static QuestionOperationsFrame getFrame(){
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listQuestions = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        txtAnswer = new javax.swing.JTextField();
        comboBoxLevel = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBoxLesson = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        radioButtonTrue = new javax.swing.JRadioButton();
        radioButtonFalse = new javax.swing.JRadioButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setResizable(true);
        setTitle("Question Operations");

        listQuestions.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listQuestions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listQuestionsMouseClicked(evt);
            }
        });
        listQuestions.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listQuestionsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listQuestions);

        jLabel1.setText("Question :");

        jLabel2.setText("Answer :");

        jLabel3.setText("Level :");

        txtQuestion.setToolTipText("Soru");
        txtQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestionActionPerformed(evt);
            }
        });

        txtAnswer.setToolTipText("Cevap");

        comboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EASY", "NORMAL", "HARD" }));
        comboBoxLevel.setToolTipText("");

        jLabel4.setText("Score :");

        txtScore.setToolTipText("Skor");

        jLabel5.setText("Lesson :");

        comboBoxLesson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("A.)");

        jLabel7.setText("B.)");

        jLabel8.setText("C.)");

        jLabel9.setText("D.)");

        radioButtonTrue.setText("True");
        radioButtonTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonTrueActionPerformed(evt);
            }
        });

        radioButtonFalse.setText("False");
        radioButtonFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonFalseActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuestion)
                            .addComponent(txtAnswer)
                            .addComponent(txtA)
                            .addComponent(txtD)
                            .addComponent(txtC)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboBoxLesson, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxLevel, javax.swing.GroupLayout.Alignment.LEADING, 0, 122, Short.MAX_VALUE)
                                    .addComponent(txtScore, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(32, 32, 32)
                                .addComponent(radioButtonTrue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonFalse)
                                .addGap(0, 401, Short.MAX_VALUE))
                            .addComponent(txtB))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(radioButtonTrue)
                    .addComponent(radioButtonFalse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuestionActionPerformed

    private void listQuestionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listQuestionsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listQuestionsValueChanged

    private void listQuestionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listQuestionsMouseClicked
        // TODO add your handling code here:
        presenter.listViewClicked();
    }//GEN-LAST:event_listQuestionsMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        presenter.deleteQuestion();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        presenter.updateQuestion();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void radioButtonTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonTrueActionPerformed
        // TODO add your handling code here:
        if(radioButtonFalse.isSelected())
            radioButtonFalse.setSelected(false);
    }//GEN-LAST:event_radioButtonTrueActionPerformed

    private void radioButtonFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonFalseActionPerformed
        // TODO add your handling code here:
        if(radioButtonTrue.isSelected())
            radioButtonTrue.setSelected(false);
    }//GEN-LAST:event_radioButtonFalseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox comboBoxLesson;
    private javax.swing.JComboBox comboBoxLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listQuestions;
    private javax.swing.JRadioButton radioButtonFalse;
    private javax.swing.JRadioButton radioButtonTrue;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtQuestion;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setTxtQuestion(String question) {
        txtQuestion.setText(question);
    }

    @Override
    public void setTxtAnswer(Object answer) {
        txtAnswer.setText(""+answer);
    }

    @Override
    public void setTxtScore(int score) {
        txtScore.setText(""+score);
    }

    @Override
    public void setTxtA(String a) {
        txtA.setText(a);
    }

    @Override
    public void setTxtB(String b) {
        txtB.setText(b);
    }

    @Override
    public void setTxtC(String c) {
        txtC.setText(c);
    }

    @Override
    public void setTxtD(String d) {
        txtD.setText(d);
    }

    @Override
    public String getTxtQuestion() {
        return txtQuestion.getText().toString();
    }

    @Override
    public Object getTxtAnswer() {
        return txtAnswer.getText();
    }

    @Override
    public String getTxtScore() {
        return txtScore.getText();
    }

    @Override
    public String getTxtA() {
        return txtA.getText();
    }

    @Override
    public String getTxtB() {
        return txtB.getText();
    }

    @Override
    public String getTxtC() {
        return txtC.getText();
    }

    @Override
    public String getTxtD() {
        return txtD.getText();    }

    @Override
    public JComboBox setLessonComboBox() {
        return comboBoxLesson;
    }

    @Override
    public JComboBox setLevelComboBox() {
        return comboBoxLevel;
    }

    @Override
    public boolean getRadioButtonIsFalse() {
        return radioButtonFalse.isSelected();}

    @Override
    public boolean getRadioButtonIsTrue() {
        return radioButtonTrue.isSelected();    }

    @Override
    public JList jListQuestions() {
        return listQuestions;
    }

    @Override
    public JRadioButton radioButtonTrue() {
        return radioButtonTrue;    }

    @Override
    public JRadioButton radioButtonFalse() {
        return radioButtonFalse;    }
    
}
