/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Presenter.TrueFalsePresenter;
import Presenter.ClassicPresenter;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Hasancan
 */
public class TrueFalseFrame extends javax.swing.JInternalFrame implements ITrueFalse{

    /**
     * Creates new form TestFrame
     */
    private static TrueFalseFrame instance = new TrueFalseFrame();
   
    private TrueFalsePresenter presenter;
    
    public TrueFalseFrame() {
        initComponents();
        this.setVisible(true);        
        presenter = new TrueFalsePresenter(this);
    }
    
    public static TrueFalseFrame getFrame(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxLesson = new javax.swing.JComboBox();
        txtAddLesson = new javax.swing.JTextField();
        comboBoxLevel = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuestionScore = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        radioBtnTrue = new javax.swing.JRadioButton();
        radioBtnfalse = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setTitle("True/False Question");

        jLabel1.setText("Select course :");

        jLabel2.setText("Add courses :");

        comboBoxLesson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtAddLesson.setToolTipText("Ders ekleyiniz..");

        comboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EASY", "NORMAL", "HARD" }));

        jLabel3.setText("Level :");

        jLabel4.setText("Question Score :");

        txtQuestionScore.setToolTipText("Soru puanı giriniz..");

        jLabel9.setText("Question :");

        txtQuestion.setToolTipText("Soru metni giriniz..");

        radioBtnTrue.setText("True");
        radioBtnTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnTrueActionPerformed(evt);
            }
        });

        radioBtnfalse.setText("False");
        radioBtnfalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnfalseActionPerformed(evt);
            }
        });

        jLabel11.setText("Answer :");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxLesson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAddLesson, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuestionScore, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnTrue)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnfalse))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuestionScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtAddLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnTrue)
                    .addComponent(radioBtnfalse)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        presenter.btnSaveTrueFalseQuestion();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void radioBtnTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnTrueActionPerformed
        // TODO add your handling code here:
        if(radioBtnfalse.isSelected())
            radioBtnfalse.setSelected(false);
    }//GEN-LAST:event_radioBtnTrueActionPerformed

    private void radioBtnfalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnfalseActionPerformed
        // TODO add your handling code here:        
        if(radioBtnTrue.isSelected())
            radioBtnTrue.setSelected(false);
    }//GEN-LAST:event_radioBtnfalseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboBoxLesson;
    private javax.swing.JComboBox comboBoxLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioBtnTrue;
    private javax.swing.JRadioButton radioBtnfalse;
    private javax.swing.JTextField txtAddLesson;
    private javax.swing.JTextField txtQuestion;
    private javax.swing.JTextField txtQuestionScore;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getLessonSelectedItem() {
        return comboBoxLesson.getSelectedItem().toString();
    }

    @Override
    public String getLevelSelectedItem() {
        return comboBoxLevel.getSelectedItem().toString();
    }
    
    @Override
    public String getTxtQuestionScore() {
        return txtQuestionScore.getText();
    }

    @Override
    public String getTxtAddLesson() {
        return txtAddLesson.getText();
    }

    @Override
    public String getTxtQuestion() {
        return txtQuestion.getText(); 
  }

    @Override
    public boolean getRadioButtonIsTrue() {
        return radioBtnTrue.isSelected();
    }
    
    @Override
    public JButton btnSaveTrueFalseQuestion() {
        return btnSave;
    }
    
    @Override
    public JComboBox setLessonComboBox() {
        return comboBoxLesson;
    }

    
}
